mdsol/mauth-client-dotnet

- CHANGELOG.md
- GlobalAssemblyInfo.cs
- Medidata.MAuth.sln
- README.md
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Core/MAuthSigningHandler.cs
- src/Medidata.MAuth.Core/Medidata.MAuth.Core.csproj
- src/Medidata.MAuth.Core/Medidata.MAuth.Core.nuspec
- src/Medidata.MAuth.Core/Options/MAuthOptionsBase.cs
- src/Medidata.MAuth.Core/Options/MAuthSigningOptions.cs
- src/Medidata.MAuth.Owin/MAuthMiddleware.cs
- src/Medidata.MAuth.Owin/MAuthMiddlewareOptions.cs
- src/Medidata.MAuth.Owin/MAuthOwinExtensions.cs
- src/Medidata.MAuth.Owin/Medidata.MAuth.Owin.nuspec
- src/Medidata.MAuth.WebApi/MAuthAuthenticatingHandler.cs
- src/Medidata.MAuth.WebApi/MAuthWebApiOptions.cs
- src/Medidata.MAuth.WebApi/Medidata.MAuth.WebApi.nuspec
- tests/Medidata.MAuth.Tests/MAuthAuthenticatorTests.cs
- tests/Medidata.MAuth.Tests/MAuthOwinTests.cs
- tests/Medidata.MAuth.Tests/MAuthTestOptions.cs
- tests/Medidata.MAuth.Tests/MAuthWebApiTests.cs
- tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj
- tests/Medidata.MAuth.Tests/TestData.cs
- tests/Medidata.MAuth.Tests/TestExtensions.cs
- tests/Medidata.MAuth.Tests/packages.config
This PR changes the used options instance in MAuthSigningHandler from MAuthOptions to MAuthSigningOptions. This change is necessary in order to not require MAuthServerUrl for the signing (which is not using this url at all).
Additionally this PR contains a fix in the OWIN middleware for the selfhosted request body being non-seekable. In these cases we replace the stream with a MemoryStream to be able to restore the body after reading it for authentication.
@mdsol/team-51 Please review and merge if it OK! Thanks!
> [MCC-259892] Change MAuthSigningHandler options to MAuthSigningOptions

- src/Medidata.MAuth.Core/project.json
- src/Medidata.MAuth.Owin/project.json
- src/Medidata.MAuth.WebApi/project.json
- tests/Medidata.MAuth.Tests/project.json
This to avoid legacy .NET project to download unnecessary NETStandard libraries.
@lschreck-mdsol, @bvillanueva-mdsol, @kenyamat please review and merge if okay.
FYI
@cabbott
> [MCC-270638] Move NETStandard.Library dependency from root dependencies node to under netstandard1.4

- CHANGELOG.md
- LICENSE.md
- README.md
- src/Medidata.MAuth.Core/project.json
- src/Medidata.MAuth.Owin/project.json
- src/Medidata.MAuth.WebApi/project.json
- tests/Medidata.MAuth.Tests/project.json
This PR changes some of the dependency references of the Core project to being frameworkAssemblies instead of plain dependencies in order to avoid framework-specific packages referenced and downloaded from NuGet.
Also it updates the documents and metadata.
@mdsol/team-51 Please review and merge it if it is 👍. Thanks!
> [MCC-273076] Fix framework assembly referencing in Core

- src/Medidata.MAuth.Core/MAuthSigningHandler.cs
- src/Medidata.MAuth.WebApi/MAuthAuthenticatingHandler.cs
This PR will remove the default HttpClientHandler instantiation if there is no inner handler provided for the `MAuthSigningHandler` as well as the `MAuthAuthenticatingHandler`.
This change is necessary in order to not cause problems with the HttpClientFactory usage.
@mdsol/team-51 Please review/merge. Thanks!
> [MCC-283382] Remove default HttpClientHandler from constructor

- README.md
This PR attempts to fix the badge links in the README because for some reason the [Public Repo Way](https://www.appveyor.com/docs/status-badges/#badges-for-projects-with-public-repositories-on-github-and-bitbucket) is not working.
After this merge, we are ready to release 2.3.0.
@mdsol/team-51 Please review/merge. Thanks!
> [MCC-310702] Update badges in README

- build/build.ps1
This corrigates the error with displaying the environment variable from the AppVeyor build.
@mdsol/team-51 Please review/merge - thanks!
> [MCC-310702] Fix build script with the AppVeyor tag name

- build/build.ps1
Hopefully this is the last fix for the build script. It fixes the conversion from the Git repo tag to a valid version number.
> Fix the tag -> version conversion in build script

- Medidata.MAuth.sln
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Core/Medidata.MAuth.Core.csproj
- src/Medidata.MAuth.Core/UtilityExtensions.cs
- tests/Medidata.MAuth.Tests/UtilityExtensionsTest.cs
- version.props
This PR adds a public utility extension class which contains some methods to call outside of the MAuth context. This can be useful in scenarios where you have to work with MAuth specific data (headers for example) and don't want to reimplement the function in your own code.
Later on this class will be extended to have more methods and ultimately the internal MAuth implementation will start to use these methods instead of the internal implementations (before you ask: of course the current internal implementations cannot be copied to this public class as they are because they have signatures and/or they are using internal data structures which do not make sense to expose).
@mdsol/team-51 Please review/merge, then I will send a new PR to have a new client version out - Thanks!
> [MCC-319001] Add a Utility extension class to support calling MAuth methods

- src/Medidata.MAuth.AspNetCore/MAuthAspNetCoreExtensions.cs
- src/Medidata.MAuth.AspNetCore/MAuthMiddleware.cs
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Owin/MAuthMiddleware.cs
- src/Medidata.MAuth.Owin/MAuthOwinExtensions.cs
- version.props
This PR resolves the issue with the incoming request body stream being not rewound after authentication.
The stream will be rewound at the end of the ASP.NET Core and OWIN middlewares to ensure the next middleware gets the stream rewound down the chain.
@mdsol/team-51 Please review/merge. Thanks!
> [MCC-328941] Fix request body content not rewound after authentication

- src/Medidata.MAuth.Core/Constants.cs
- tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj
- tests/Medidata.MAuth.Tests/UtilityExtensionsTest.cs
- version.props
As the title says, this PR will remove the restriction on the MAuth uuid validation to be only version 4.
@mdsol/team-51 Please review and merge - then we can release it to the wild! Thanks!
> [MCC-365432] Change uuid validation to accept non-v4 uuids

- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthRequestRetrier.cs
- version.props
The `exception` field in `MAuthRequestRetrier` can be modified from multiple threads, additionally even when an exception would be thrown, the `Request` property would likely be wrong, and the `Responses` contained responses from other failed & successful requests.
> [MCC-422186] Fix concurrency issue in MAuthRequestRetrier

- CHANGELOG.md
- README.md
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthRequestRetrier.cs
- src/Medidata.MAuth.Core/Medidata.MAuth.Core.csproj
- version.props
This PR contains the caching mechanism for MAuth authentication that involves requests to the MAuth server.
The solution sets the expiration time based on the MAuth server response cache header (if it is not set, it will be 1 hour by default).
I will update the documentation as well.
> [MCC-465787] Add caching for the MAuth server communication

- src/Medidata.MAuth.AspNetCore/MAuthMiddleware.cs
- src/Medidata.MAuth.AspNetCore/Medidata.MAuth.AspNetCore.csproj
- tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj
This PR is to fix the issue with .netcore 3.0 support which was reported in this issue:
https://github.com/mdsol/mauth-client-dotnet/issues/48
- Updated `EnableRewind()` to `EnableBuffering()`
- Also updated few other aspnetcore packages
Please review:
@lgabriel-mdsol 
@bvillanueva-mdsol
> [MCC-543272] Fix the issue for .netcore 3.0 support 

- src/Medidata.MAuth.AspNetCore/MAuthAspNetCoreExtensions.cs
- src/Medidata.MAuth.AspNetCore/MAuthMiddleware.cs
- src/Medidata.MAuth.AspNetCore/Medidata.MAuth.AspNetCore.csproj
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthCoreV2.cs
- src/Medidata.MAuth.Core/Medidata.MAuth.Core.csproj
- src/Medidata.MAuth.Core/UtilityExtensions.cs
- src/Medidata.MAuth.Owin/MAuthMiddleware.cs
- src/Medidata.MAuth.Owin/MAuthOwinExtensions.cs
- src/Medidata.MAuth.Owin/Medidata.MAuth.Owin.csproj
- src/Medidata.MAuth.WebApi/MAuthAuthenticatingHandler.cs
- src/Medidata.MAuth.WebApi/MAuthWebApiExtensions.cs
- src/Medidata.MAuth.WebApi/Medidata.MAuth.WebApi.csproj
Recently, there had been some problem of  deadlocks on Authentication path. Therefore, this PR adds `ConfigureAwait(false)` on all of the possible cases of Authentication path to resolve those issues.
Also added `ConfigureAwaitCheck.Analyzer` to find out `await` without `ConfigureAwait(false)`
Please review:
@danielloganking 
@mdsol/architecture-enablement
> [MCC-555460] Fix deadlocks issues 

- CHANGELOG.md
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Core/MAuthCoreV2.cs
- src/Medidata.MAuth.Core/MAuthRequestRetrier.cs
- tests/Medidata.MAuth.Tests/MAuthCoreV2Tests.cs
- tests/Medidata.MAuth.Tests/Mocks/RequestDataV2/DELETE.json
- tests/Medidata.MAuth.Tests/Mocks/RequestDataV2/GET.json
- tests/Medidata.MAuth.Tests/Mocks/RequestDataV2/POST.json
- tests/Medidata.MAuth.Tests/Mocks/RequestDataV2/POSTWithBinaryData.json
- tests/Medidata.MAuth.Tests/Mocks/RequestDataV2/PUT.json
Recently, a bug was reported by @lgabriel-mdsol that when latest "mauth-client-dotnet" was used for Authentication, it is throwing forbidden `403` error.
**Scenario** : By default, sign on is with both `MWS` and `MWSV2` protocol. Therefore, during authentication, it checks for `MWSV2` protocol first and if it finds the header, it tries to verify `MWSV2` header.
**Problem**
During the process of verification, it has to fetch `publickey` from mauth. The mauth url is same for both protocol i.e. `<mauth_url>/mauth/v1/security_tokens/<*.json>`. And, during the fetching process, it includes both `MWS` and `MWSV2` protocol. And, this process was throwing `403` i.e. forbidden error.
**Investigation**
During this process thanks to @lgabriel-mdsol (initially) and later @cmcinnes-mdsol , we …
> [MCC-555926] Fixed handling of MWSV2 header throwing 403 error.

- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- tests/Medidata.MAuth.Tests/MAuthAuthenticatorTests.cs
@ykitamura-mdsol pointed out that the log message in `mauth-client-dotnet` is not the same as other language and needs to be same in order to be searched for the logs later in sumologic.
Log message in `mauth-jvm-client`: https://github.com/mdsol/mauth-jvm-clients/blob/70d1767d744e46aa26aecbc3bafc91771c7565bd/modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java#L94
Log message in `mauth-client-ruby`: https://github.com/mdsol/mauth-client-ruby/blob/v5.0.2/lib/mauth/client/authenticator_base.rb#L51-L53
Therefore, this PR is to refactor the log message it to have the same key phrase which is: `Mauth-client attempting to authenticate request from app`
Please review:
@ykitamura-mdsol 
@mdsol/team-51
> [Refactor] Refactor log message to same as ruby, java and python

- CHANGELOG.md
- README.md
- src/Medidata.MAuth.AspNetCore/Medidata.MAuth.AspNetCore.csproj
- tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj
- version.props
Recently @awiesendangermdsol  incurred an issue and provided feedback that in updated MAuth , we have mentioned as support aspnetcore 2.0 and onwards but we had mix of references of  `Microsoft.AspNetcore.....2.2...` also.
Therefore, this PR is to address that problem and update all the aspnetcore versions to `2.1` which is LTS.
Please review:
@hkurniawan-mdsol 
@awiesendangermdsol
> [Fix] Update aspnetcore version to 2.1 LTS 

- src/Medidata.MAuth.Core/Medidata.MAuth.Core.csproj
One more, please 🙏 
Update MEL in `Medidata.MAuth.Core` to 2.1
Remove not used `MEL.Debug` and `MEL.Console` 
@awiesendangermdsol 
@hkurniawan-mdsol 
@mdsol/architecture-enablement
> Update  MEL library in Medidata.MAuth.Core to 2.1 

- CHANGELOG.md
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthRequestRetrier.cs
- tests/Medidata.MAuth.Tests/Infrastructure/MAuthServerHandler.cs
- tests/Medidata.MAuth.Tests/MAuthAuthenticatorTests.cs
- tests/Medidata.MAuth.Tests/Medidata.MAuth.Tests.csproj
As discussed in this [doc](https://docs.google.com/document/d/1UsKJfZeDJb3cbvi0B-z-KMXHrNEGo-GKhXi2k4OnMxU/edit#heading=h.k5ec2aaqcyc0)
and same as in ruby [mdsol/mauth-client-ruby#38](https://github.com/mdsol/mauth-client-ruby/pull/38), this PR updates the logic to fall back to V1 authentication when V2 authentication fails.
Please review:
@mdsol/team-51
> [MCC-575471] Fall back to V1 authentication when V2 authentication fails

- CHANGELOG.md
- src/Medidata.MAuth.Core/Constants.cs
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Core/MAuthCoreV2.cs
- tests/Medidata.MAuth.Tests/MAuthCoreExtensionsTests.cs
- tests/Medidata.MAuth.Tests/MAuthCoreV2Tests.cs
- version.props
This PR implements
- Removal of "double encoding" of query string parameters and uses the same approach as that of other languages as `ruby, python and java`.  (Note: Encodes `%2B` -> `%20`  to match that of other languages.)
- Adding normalization of the `requestUri path`.
- Updated the `Changelog` and `version.props`.
- Updated the log message during  Authentication to same as that of other langs `ruby`and `python`.
Please review:
@mdsol/libraries_dotnet
> [MCC-638856] Remove double encoding for query params and normalize path for V2 signature

- src/Medidata.MAuth.AspNetCore/MAuthMiddleware.cs
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Owin/MAuthMiddleware.cs
- src/Medidata.MAuth.WebApi/MAuthAuthenticatingHandler.cs
- tests/Medidata.MAuth.Tests/Infrastructure/NonSeekableStream.cs
- tests/Medidata.MAuth.Tests/Infrastructure/RequestBodyAsNonSeekableMiddleware.cs
As stated in the title.
This PR is for:
- Updating private variable prefixed with `_`
- Remove `this` keyword when referring to private variable.
Please review:
@mdsol/libraries_dotnet 
@hkurniawan-mdsol 
@mdsol/architecture-enablement
> [Housekeeping] Prefix private variable with underscore 

- CHANGELOG.md
- README.md
- src/Medidata.MAuth.Core/MAuthSigningHandler.cs
- src/Medidata.MAuth.Core/Models/MAuthVersion.cs
- src/Medidata.MAuth.Core/Options/MAuthSigningOptions.cs
- tests/Medidata.MAuth.Tests/MAuthSigningHandlerTests.cs
- version.props
This PR is for this story:https://jira.mdsol.com/browse/MCC-638046
It includes:
- Replace `DisableV1` option in Signing with `SigningOptions` parameter which enumerations of protocol versions
as `SignVersions = MAuthVersion.MWS | MAuthVersion.MWSV2`
- Defaults the signing to `MWSV2` when `SignVersions` is not provided.
- Updated `CHANGELOG` and `README`.
Notes: Since not all apps are updated to latest, please use v1 when you experience authentication failures.
Relevant PR from:
Ruby: https://github.com/mdsol/mauth-client-ruby/pull/40
Python: https://github.com/mdsol/mauth-client-python/pull/19
Java: https://github.com/mdsol/mauth-jvm-clients/pull/128
Please review:
@mdsol/libraries_dotnet 
@mdsol/team-51
> [MCC-638046] Make the signing protocol versions configurable

- CHANGELOG.md
- CONTRIBUTING.md
- build/build.ps1
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- tests/Medidata.MAuth.Tests/Infrastructure/AssertSigningHandler.cs
- tests/Medidata.MAuth.Tests/Infrastructure/MAuthServerHandler.cs
- tests/Medidata.MAuth.Tests/Infrastructure/TestExtensions.cs
- tests/Medidata.MAuth.Tests/MAuthAspNetCoreTests.cs
- tests/Medidata.MAuth.Tests/MAuthAuthenticatorTests.cs
- tests/Medidata.MAuth.Tests/MAuthOwinTests.cs
- tests/Medidata.MAuth.Tests/MAuthProtocolSuiteTests.cs
- tests/Medidata.MAuth.Tests/MAuthWebApiTests.cs
- tests/Medidata.MAuth.Tests/ProtocolTestSuite/AuthenticationHeader.cs
- tests/Medidata.MAuth.Tests/ProtocolTestSuite/ProtocolTestSuiteHelper.cs
- tests/Medidata.MAuth.Tests/ProtocolTestSuite/SigningConfig.cs
- tests/Medidata.MAuth.Tests/ProtocolTestSuite/UnSignedRequest.cs
- tests/Medidata.MAuth.Tests/UtilityExtensionsTest.cs
- tests/Medidata.MAuth.Tests/xunit.runner.json
Following the changes made in https://github.com/mdsol/mauth-client-python/pull/15
and https://github.com/mdsol/mauth-client-ruby/pull/39
Updates includes
- Add [mauth-protocol-test-suite](https://github.com/mdsol/mauth-protocol-test-suite)
- Updated Sorting part in `BuildEncodedQueryParams` 
Please review 
@mdsol/libraries_dotnet 
@mdsol/team-51
> [MCC-575820] Incorporate protocol test suite and implement

- CHANGELOG.md
- README.md
- src/Medidata.MAuth.Core/MAuthCore.cs
- src/Medidata.MAuth.Core/MAuthCoreExtensions.cs
- src/Medidata.MAuth.Core/MAuthCoreV2.cs
- src/Medidata.MAuth.Core/Options/MAuthOptionsBase.cs
- src/Medidata.MAuth.Core/Options/MAuthSigningOptions.cs
- tests/Medidata.MAuth.Tests/MAuthCoreTests.cs
- tests/Medidata.MAuth.Tests/MAuthOwinTests.cs
- tests/Medidata.MAuth.Tests/MAuthWebApiTests.cs
- version.props
Follow-up on #67.
Related to https://jira.mdsol.com/browse/MCC-655130.
Inflate private key upon set in the `_Options` classes in order to avoid reading it from disk every time a request is signed.
> [MCC-655130] Inflate private key upon set in options classes.

- CHANGELOG.md
- src/Medidata.MAuth.Core/AsyncLazy.cs
- src/Medidata.MAuth.Core/CacheExtensions.cs
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- src/Medidata.MAuth.Core/MAuthRequestRetrier.cs
If the application info for a particular application uuid has not been cached in memory, it's possible for multiple threads to enter the cache factory method and send outbound requests for the data from the mAuth service.  When there is a high number of concurrent requests executing this logic, there can be significant blocking within the application until the requested info gets cached in memory.
The two concerns are:
- Multiple threads able to call the cache item factory method when application info is not already cached for a specific application uuid
- A new HttpClient (and associated resources) created for each outbound request
During a restart of our application, requests get queued on the web server while the new process starts up.  Once the application has started, it gets the …
> [MCC-721105] Avoid Multiple Outbound Requests for Application Info When Not Already Cached

- .gitattributes
- .gitmodules
- CONTRIBUTING.md
- Medidata.MAuth.sln
- appveyor.yml
- build/build.ps1
- tests/Medidata.MAuth.Tests/ProtocolTestSuite/ProtocolTestSuiteHelper.cs
[Jira story](https://jira.mdsol.com/browse/MCC-652120)
This PR is for incorporating [mauth protocol test suite](https://github.com/mdsol/mauth-protocol-test-suite) into this "mauth-client-dotnet" repository as submodule.
It includes:
- Add `mauth-protocol-test-suite` as git submodule.
- Update contributing doc.
- Updated and verified all the unit tests run with `dotnet test`.
Please review:
@mdsol/architecture-enablement
> [MCC-652120] Incorporate protocol test suite as submodule

- .github/workflows/publish.yaml
As the title says, this argument supposedly causing issues with the tests.
@mdsol/enablement-dotnet please.
> Remove --no-build to attempt to fix the workflow

- CHANGELOG.md
- src/Medidata.MAuth.Core/MAuthAuthenticator.cs
- version.props
This PR switches the current default 1 hour to 5 minutes of the public key caching in case when the MAuth server does not have any (or has invalid) caching instruction headers.
@mdsol/enablement-dotnet
> [MCC-805831] Switch key caching to 5 minutes
